"""
schemas.py

Pydantic models for the Career Roadmap module.
"""

from typing import List
from pydantic import BaseModel


class CareerRoadmap(BaseModel):
    """
    Structured career roadmap generated by AI.
    """

    target_role: str

    current_strengths: List[str]

    skills_to_learn: List[str]

    recommended_projects: List[str]

    recommended_certifications: List[str]

    learning_resources: List[str]

    weekly_plan: List[str]

    estimated_duration: str

    motivation: str